## Important Numpy Functions ##

In [169]:
import numpy as np

## np.sort ##
return a sorted copy of an array

there may be question? why not to use sorted function built in python? ---> one reason is it returns list whereas np.sort returns a numpy array and another reason is its(np.sort) perfomance is very fast on larger dataset as compared sorted() function

In [170]:
#lets create one numpy array
a = np.random.randint(1,100,15)
a

array([74, 36, 98, 34, 94, 64, 24, 77, 97, 31, 41, 73, 91, 28, 90],
      dtype=int32)

In [171]:
# lets sort the above array
np.sort(a) #default is ascending

array([24, 28, 31, 34, 36, 41, 64, 73, 74, 77, 90, 91, 94, 97, 98],
      dtype=int32)

In [172]:
#for sorting in descending order
np.sort(a)[::-1]

array([98, 97, 94, 91, 90, 77, 74, 73, 64, 41, 36, 34, 31, 28, 24],
      dtype=int32)

In [173]:
# lets try with 2d array
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[65, 82, 99, 44],
       [61, 84, 21, 69],
       [36, 73, 26, 74],
       [ 5, 51, 66,  8],
       [78, 39, 40, 42],
       [90, 43, 80, 80]], dtype=int32)

In [174]:
np.sort(a) #default is axis=1 perform operaion row wise

array([[44, 65, 82, 99],
       [21, 61, 69, 84],
       [26, 36, 73, 74],
       [ 5,  8, 51, 66],
       [39, 40, 42, 78],
       [43, 80, 80, 90]], dtype=int32)

In [175]:
np.sort(a,axis=0) # axis = 0 perform operation column wise

array([[ 5, 39, 21,  8],
       [36, 43, 26, 42],
       [61, 51, 40, 44],
       [65, 73, 66, 69],
       [78, 82, 80, 74],
       [90, 84, 99, 80]], dtype=int32)

In [176]:
#lets try one example with 3d array what will happen
a = np.random.randint(1,100,24).reshape(4,3,2)   # collection of 4 matrix of size 3,2
a

array([[[29, 42],
        [24, 17],
        [50, 93]],

       [[ 6, 62],
        [74, 79],
        [60, 84]],

       [[13, 99],
        [23, 23],
        [91, 65]],

       [[36, 42],
        [28, 70],
        [43, 31]]], dtype=int32)

In [177]:
np.sort(a,axis = 1) #sorting array columnwise

array([[[24, 17],
        [29, 42],
        [50, 93]],

       [[ 6, 62],
        [60, 79],
        [74, 84]],

       [[13, 23],
        [23, 65],
        [91, 99]],

       [[28, 31],
        [36, 42],
        [43, 70]]], dtype=int32)

In [178]:
np.sort(a,axis=2) #soring array row wise(default is always row wise for any dimensional array)

array([[[29, 42],
        [17, 24],
        [50, 93]],

       [[ 6, 62],
        [74, 79],
        [60, 84]],

       [[13, 99],
        [23, 23],
        [65, 91]],

       [[36, 42],
        [28, 70],
        [31, 43]]], dtype=int32)

## np.append() ##

np.append() function in numpy returns a new array with the specified elements appended.
whereas list.append() method in python list modifies the original list by adding specified element to it.

In [179]:
a = np.random.randint(0,100,10)
a

array([22, 29, 63, 59, 43, 56, 82, 53, 22, 25], dtype=int32)

In [180]:
# lets append 20 to it 
np.append(a,20)

array([22, 29, 63, 59, 43, 56, 82, 53, 22, 25, 20])

In [181]:
#lets create a 2d matrix
a = np.random.randint(0,100,12).reshape(4,3)
a

array([[37, 60, 40],
       [92, 86, 17],
       [53,  2, 67],
       [37, 64,  1]], dtype=int32)

In [182]:
#lets append a new row into it 
np.append(a,[10,20,30])

array([37, 60, 40, 92, 86, 17, 53,  2, 67, 37, 64,  1, 10, 20, 30])

in above problem append function convert existing array from 2d to 1d and then append the values so we have to define axis

In [183]:
np.append(a,[[10,20,30]],axis = 0) # adding as a row #dont be confused axis = 0 means rows but perfroming operation columwise

array([[37, 60, 40],
       [92, 86, 17],
       [53,  2, 67],
       [37, 64,  1],
       [10, 20, 30]])

In [184]:
np.append(a,[[10],[20],[30],[40]],axis =1) #making shape 1x4(1 column 4 rows to add as column)

array([[37, 60, 40, 10],
       [92, 86, 17, 20],
       [53,  2, 67, 30],
       [37, 64,  1, 40]])

### Summary of `axis` in NumPy

#### General Rule:
- **`axis=0`**: Refers to **rows** (vertical direction).
- **`axis=1`**: Refers to **columns** (horizontal direction).

#### Behavior by Operation:
1. **Aggregation Operations (e.g., `sum`, `mean`, `min`, `max`)**:
   - **`axis=0`**: Collapses rows (performs operation **column-wise**).
   - **`axis=1`**: Collapses columns (performs operation **row-wise**).

2. **Sorting Operations (e.g., `np.sort`)**:
   - **`axis=0`**: Sorts **column-wise** (each column sorted independently).
   - **`axis=1`**: Sorts **row-wise** (each row sorted independently).

3. **Concatenation Operations (e.g., `np.append`, `np.concatenate`)**:
   - **`axis=0`**: Stacks arrays **vertically** (adds rows).
   - **`axis=1`**: Stacks arrays **horizontally** (adds columns).

#### Key Takeaways:
- **`axis=0`**:
  - In aggregation/sorting: Operates **column-wise** (across rows).
  - In concatenation: Adds **rows** (vertical stacking).
- **`axis=1`**:
  - In aggregation/sorting: Operates **row-wise** (across columns).
  - In concatenation: Adds **columns** (horizontal stacking).

## np.concatenate() ##

The np.concatenate() function is used to join two or more arrays along an existing axis. You can specify the axis along which you want to concatenate the arrays using the axis parameter.

- **`np.concatenate()`**: Joins arrays along an existing axis (you specify which axis).
- **`np.vstack()`**: Stacks arrays vertically (row-wise), equivalent to `np.concatenate()` along `axis=0`.
- **`np.hstack()`**: Stacks arrays horizontally (column-wise), equivalent to `np.concatenate()` along `axis=1`. 

using concatenate we can avoid using vstack() and hstack()

In [185]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [186]:
b = np.array([[5,6]])
b

array([[5, 6]])

In [187]:
# now concatenate both
np.concatenate((a,b),axis=0) #add rows(like in append)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [188]:
#np.concatenate((a,b),axis=1) #add columns(like in append)
# np.concatenate((a,b),axis=1)
# this will give error because number of rows are not same in both array
#Rows do NOT match:
#a has 2 rows
#b has 1 row


In [189]:
# b should be reshaped or transpose
b = np.transpose(b)
c = np.concatenate((a,b),axis=1)

#Fix: make both arrays 2D
Convert a to a column:

In [190]:
#To fix it : To add columns, b must have 2 rows: ##rows must be equal
a = np.array([1, 2, 3]).reshape(-1, 1)
b = np.array([[5],
              [6],
              [7]])

c = np.concatenate((a, b), axis=1)
print(c)

[[1 5]
 [2 6]
 [3 7]]


# If a should be a 2D table
Define it like this:

In [191]:
a = np.array([[1, 2],
              [3, 4],
              [5, 6]])

b = np.array([[7],
              [8],
              [9]])

c = np.concatenate((a, b), axis=1)
print(c)


[[1 2 7]
 [3 4 8]
 [5 6 9]]


In [192]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5],
              [6]])

c = np.concatenate((a, b), axis=1)
print(c)

[[1 2 5]
 [3 4 6]]


### Key rule
To use axis=1:
Arrays must be 2D
Same number of rows
Shapes like:

a → (3,2)

b → (3,1)

## Quick mental model
| Shape | Meaning        |
| ----- | -------------- |
| (3,)  | 1D → no axis=1 |
| (3,1) | 2D column      |
| (1,3) | 2D row         |

a = a.reshape(-1, 1)

## np.unique() ##

- **`np.unique()`**: Finds the unique elements of an array and returns them in sorted order.
- It can also return the indices of the unique elements and the counts of their occurrences.

In [193]:
a = [1,1,1,2,2,2,3,3,3,3,3,4,5,6,7,7,7]
print(a)
b = [[1,2,3,1],[1,2,3,2]]
print(b)

[1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 4, 5, 6, 7, 7, 7]
[[1, 2, 3, 1], [1, 2, 3, 2]]


In [194]:
np.unique(a)

array([1, 2, 3, 4, 5, 6, 7])

In [195]:
np.unique(b)

array([1, 2, 3])

## np.expand_dims() ##

- **`np.expand_dims()`**: Expands the shape of an array by inserting a new axis at the specified position.
- This is useful for adding dimensions to arrays for broadcasting or alignment purposes.

In [196]:
a = np.array([10,20,30,40,50,60,70]) #--> 1d array(vector)

In [197]:
np.expand_dims(a,axis=0) #add column

array([[10, 20, 30, 40, 50, 60, 70]])

the above output is matrix of shape (1,7)

In [198]:
np.expand_dims(a,axis=1) #add(expand) rows

array([[10],
       [20],
       [30],
       [40],
       [50],
       [60],
       [70]])

In [199]:
np.expand_dims(a,axis=1).shape

(7, 1)

## Using `np.expand_dims()` in Machine Learning

In machine learning, models usually expect inputs in batches. When making predictions, a model takes input and provides output. For instance, if we have a model that accepts goals/assists and age and predicts a footballer's market value, most machine learning algorithms expect multiple inputs at the same time, not just data for one player.

If you have data for a single player with shape `(2,)` (let’s say goals/assists and age), this shape means you only have one example. If your model expects batch inputs, you need to transform it to include a batch dimension. Using `np.expand_dims()` can add this dimension, changing the shape from `(2,)` to `(1, 2)`. Now, it looks like you have a batch of one player data point.

Here's how it works in practice:

```python
import numpy as np

# Single player data: [g/a, age]
player_data = np.array([30, 25])

# Expand dimensions to simulate a batch of one
player_data_batch = np.expand_dims(player_data, axis=0)

print(player_data_batch.shape)  # Output: (1, 2)


## np.where() ##

The `np.where()` function in NumPy is a versatile tool for conditional selection and manipulation of array elements. It allows for the evaluation of a condition and provides options for choosing values based on whether the condition is `True` or `False`.

## Syntax:
```python
np.where(condition, [x, y])
condition: A boolean expression or an array-like structure that evaluates to True or False for each element in an array.
x (optional): An array or scalar specifying the values to be returned where the condition is True.
y (optional): An array or scalar specifying the values to be returned where the condition is False.

In [200]:
# lets do the example of np.where() which is one of the very useful function
a

array([10, 20, 30, 40, 50, 60, 70])

In [201]:
# now find all the indices with value greater than 40
np.where(a>40)

(array([4, 5, 6]),)

In [202]:
#replace all the values > 40 with 0
np.where(a>40,0,a) #return 0 where condition is true and a(existing value from array a ) if condition is false

array([10, 20, 30, 40,  0,  0,  0])

In [203]:
# replace all even value with o
np.where(a%2 == 0,0,a)

array([0, 0, 0, 0, 0, 0, 0])

Q. Given an array of integers, use np.where() to create a new array that labels each element as 'Even' or 'Odd'.

In [204]:
arr = np.array([1,2,3,4,5,6])
np.where(arr%2 == 0 ,"Even","Odd")

array(['Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even'], dtype='<U4')

Q. Replace Negative Values: Given an array of integers, use np.where() to replace all negative values with zero.

In [205]:
arr = np.array([-5, 3, -1, 7, -2, 8])
np.where(arr < 0,0,arr)

array([0, 3, 0, 7, 0, 8])

Q. Conditional Transformation: Given two arrays of the same shape, use np.where() to create a new array that takes elements from the first array if they are positive and from the second array if they are non-positive.

In [206]:
arr1 = np.array([1, -2, 3, -4, 5])
arr2 = np.array([-1, 2, -3, 4, -5])
np.where(arr1>0,arr1,arr2)

array([1, 2, 3, 4, 5])

## np.argmax()
np.argmax() function returns indices of the max element of the array in a particular axis.

This function is also very very important and useful 

In [207]:
a

array([10, 20, 30, 40, 50, 60, 70])

In [208]:
np.argmax(a) #returns the maximum element index

np.int64(6)

In [209]:
a[np.argmax(a)]  #max value

np.int64(70)

Q. Max Value in a 2D Array: How can you use np.argmax() to find the index of the maximum value in a 2-dimensional array like [[1, 2, 3], [4, 5, 6]]?

In [210]:
a = np.array([[1,2,3],[4,5,6]])
np.argmax(a) #returns the index of maximum element in the flattened array

np.int64(5)

This function convert 2d array into 1d and returns a index with max value but we can find max value along the axis as :

In [211]:
np.argmax(a,axis=0) #perform operation column wise

array([1, 1, 1])

In [212]:
np.argmax(a,axis=1) #perfom operation rowwise

array([2, 2])

Q. Write a function that returns both the maximum value and its index in a given 1-dimensional array using np.argmax()

In [213]:
a = np.array([3, 1, 5, 2, 4])
print(f"max value index : {np.argmax(a)}")
print(f"max value  : {a[np.argmax(a)]}")

max value index : 2
max value  : 5


## np.argmin()
oppiste of np.argmax()

## np.cumsum()
np.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis .
keep in mind that it is not like sum rather it returns array with cummulative sum (summing with previous value)
for example we have a goal of cristiano ronaldo in match as [2,3,1,5,1,0,0,2,1].
then the cummulative sum is like [2,2+3,2+3+1,....]

In [214]:
#example 
ronaldo_last10_goals = ronaldo_goals = np.array([1, 2, 3, 1, 0, 0, 2, 1, 1, 0])
ronaldo_last10_goals_cummulative = np.cumsum(ronaldo_last10_goals)
ronaldo_last10_goals_cummulative

array([ 1,  3,  6,  7,  7,  7,  9, 10, 11, 11])

using this we can see the total goals of ronaldo at any point like after 8th game total goal was 10. This is very useful function

In 2d arrays, if axis is not defined then it will convert 2d array to 1d , we should specify axis to find the cummulative sum of that axis.

## np.cumprod()
same like sum but for product

## np.percentile()
used  to compute the nth percentile of given data(numpy array)

In [215]:
a = np.random.randint(0,101,15)
a

array([ 43,  29,  57,  90,  55,  22,  12,  40, 100,  92,   4,  99,  83,
        59,  90], dtype=int32)

In [216]:
#now finding 100th percentile
np.percentile(a,100)   #100 th percentile means always the maximum value

np.float64(100.0)

In [217]:
# 0th percentile
np.percentile(a,0) #minimum value

np.float64(4.0)

In [218]:
# 50th percentile (median)
np.percentile(a,50)

np.float64(57.0)