### Creating Numpy Arrays

In [1]:
# Create a One-dimensional Array
# Importing NumPy Array np.array
import numpy as np

a = np.array([1,2,3])
print(a)
# this is a one dimenisonal array

[1 2 3]


In [2]:
# the dimensions of the array.
a.shape

(3,)

In [3]:
# the number of axes (dimensions) of the array.
a.ndim

1

In [4]:
# the total number of elements of the array. 
a.size

3

In [5]:
# an object describing the type of the elements in the array. 
a.dtype

dtype('int64')

In [6]:
# the size in bytes of each element of the array. 
a.itemsize

8

In [7]:
# the buffer containing the actual elements of the array. Normally, we won’t need to use 
a.data

In [8]:
# Creating an array using np.array() method
arr = np.array([10, 20, 30, 40, 50])
print(arr)

# create a another One-dimensional Array with 10 elements
b=np.array([1,2,3,4,5,6,7,8,9])
print(b)

[10 20 30 40 50]
[1 2 3 4 5 6 7 8 9]


# Creating an array using Multi-dimensional 2D and 3D array method

In [9]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
b.shape

(2, 3)

In [11]:
# create a 2d array with shape 3*3
np.array([[1,2,3],[1,2,3],[1,2,3]]).ndim

2

In [12]:
# create a another 2d array of shape 4*4
np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]])

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [13]:
# create a another 2d array of 2*3
np.array([[1,2,3],[1,2,3]]).ndim

2

In [14]:
#create a 3d array with shape 2*2*2
np.array([[[1,2],[1,2]],[[1,2],[1,2]]]).ndim

3

In [15]:
# create a 3d array with 3*3*3 shape
np.array([[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]]]).ndim

3

# Note 
2 means 1d 

2*2 means 2d

2*2*2 means 3d

2*2*2*2 means 4d array

In [16]:
# create a array with a shape 3*3*3
np.array([[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]]]).shape

(3, 3, 3)

In [17]:
# create a array with a shape 2*1*2
np.array([[[1,2]],[[1,2]]]).shape

(2, 1, 2)

In [18]:
# dtype
np.array([1,2,3], dtype=float)

array([1., 2., 3.])

In [19]:
# create with a dtype a int
# dtype
np.array([1,2,3], dtype=int)

array([1, 2, 3])

### Initialize a Python NumPy Array Using Special Functions
NumPy provides several built-in functions to generate arrays with specific properties.

- np.zeros(): Creates an array filled with zeros.
- np.ones(): Creates an array filled with ones.
- np.full(): Creates an array filled with a specified value.
- np.arange(): Creates an array with values that are evenly spaced within a given range.
- np.linspace(): Creates an array with values that are evenly spaced over a specified interval.

In [20]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [21]:
# create a array using a arrange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [22]:
x = 5          # integer scalar
y = 3.14       # float scalar
z = True       # boolean scalar

In [23]:
# with reshape
np.arange(16).ndim

1

In [24]:
# with reshape
np.arange(16).reshape(2,2,2,2).ndim

4

In [25]:
# your task create a 45 elements array and then reshape it 
# with reshape
np.arange(45).reshape(3,3,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]]])

In [26]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
# np.random
np.random.random((3,4))

array([[0.37257278, 0.56908117, 0.55826299, 0.4555399 ],
       [0.15921076, 0.21106153, 0.12943268, 0.37502494],
       [0.02888859, 0.77476838, 0.63177765, 0.5479351 ]])

In [29]:
# Creates an array with values that are evenly spaced over a specified interval.
# np.linspace(0, 1, 5)  # start, stop, num
# np.linspace 
np.linspace(-10, 10, dtype=int)

array([-10, -10, -10,  -9,  -9,  -8,  -8,  -8,  -7,  -7,  -6,  -6,  -6,
        -5,  -5,  -4,  -4,  -4,  -3,  -3,  -2,  -2,  -2,  -1,  -1,   0,
         0,   1,   1,   1,   2,   2,   3,   3,   3,   4,   4,   5,   5,
         5,   6,   6,   7,   7,   7,   8,   8,   9,   9,  10])

In [30]:
# np.linspace
np.linspace(-5,5,10,dtype=int)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  5])

In [31]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [32]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [33]:
# ndim
a3.ndim

3

In [34]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [35]:
# size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [36]:
# itemsize
a3.itemsize

8

In [37]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


### Changing Datatype

In [38]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [39]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [40]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [42]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [43]:
# vector operations
# arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

### Array Functions

In [44]:
a1 = np.random.random((3,3))
a1

array([[0.01881194, 0.72678817, 0.31727008],
       [0.80759915, 0.35132839, 0.46260377],
       [0.9056578 , 0.1394909 , 0.86717138]])

In [45]:
a1 = np.round(a1*100)
a1

array([[ 2., 73., 32.],
       [81., 35., 46.],
       [91., 14., 87.]])

In [46]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.prod(a1,axis=0)

array([ 14742.,  35770., 128064.])

In [47]:
np.max(a1)

np.float64(91.0)

In [48]:
np.min(a2)

np.int64(12)

In [49]:
# mean/median/std/var
np.var(a1)

np.float64(965.7283950617285)

In [50]:
# trigonomoetric functions
np.sin(a1)

array([[ 0.90929743, -0.67677196,  0.55142668],
       [-0.62988799, -0.42818267,  0.90178835],
       [ 0.10598751,  0.99060736, -0.82181784]])

In [51]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [52]:
# log and exponents
np.exp(a1)

array([[7.38905610e+00, 5.05239363e+31, 7.89629602e+13],
       [1.50609731e+35, 1.58601345e+15, 9.49611942e+19],
       [3.31740010e+39, 1.20260428e+06, 6.07603023e+37]])

### np.ceil() → Ceiling

Definition: Rounds each number UP to the nearest integer.

Always goes toward +∞, no matter what.

In [53]:
import numpy as np

arr = np.array([1.2, 2.7, -1.5, -2.3])
arr

array([ 1.2,  2.7, -1.5, -2.3])

In [54]:
np.ceil(arr)

array([ 2.,  3., -1., -2.])

### np.floor() → Floor

Definition: Rounds each number DOWN to the nearest integer.

Always goes toward -∞.

In [55]:
np.floor(arr)

array([ 1.,  2., -2., -3.])

### np.round() → Round (to nearest)

Definition: Rounds each number to the nearest integer.

If decimal = 0.5 → rounds to nearest even integer (NumPy behavior).

In [56]:
np.round(arr)

array([ 1.,  3., -2., -2.])

### Indexing and Slicing

In [57]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [58]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
a2[1,0]

np.int64(4)

In [61]:
a2[1,2]

np.int64(6)

In [62]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [63]:
a3[1,0,1]

np.int64(5)

In [64]:
a3[0,1,0]

np.int64(2)

In [65]:
### find the elements 7
a3[1,1,1]

np.int64(7)

In [66]:
# find elements 3
a3[0,0,1]

np.int64(1)

In [67]:
# whats the output
a3[1,1,0]

np.int64(6)

In [68]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
a1[2:5:2]

array([2, 4])

In [70]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [71]:
a2[0:2,1:2]

array([[1],
       [5]])

In [72]:
# find the elements 9 and like aobove
a2[2,1:3]

array([ 9, 10])

In [73]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [74]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [75]:
a2[:,2:3]

array([[ 2],
       [ 6],
       [10]])

In [76]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [77]:
### now make a question and solve it 
# find the elements 14 and 17
a2[1,2:4]

array([6, 7])

In [78]:
a2[1,::3]

array([4, 7])

In [79]:
a2[0,:]

array([0, 1, 2, 3])

In [80]:
a2[:,2]

array([ 2,  6, 10])

In [81]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [82]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [83]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [84]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [85]:
a3[0,1,:]

array([3, 4, 5])

### Iterating

In [86]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [87]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [88]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [89]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [90]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [91]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [92]:
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [93]:
# ravel
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [94]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [95]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [96]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [97]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [98]:
from PIL import Image
import numpy as np

# Open an image file (use a relative or absolute path)
# Load image
img = Image.open("OIP.jpeg")  # your image file

print(f"Filename: {img.filename}")
print(f"Format: {img.format}")
print(f"Mode: {img.mode}")
print(f"Size (width, height): {img.size}")

# Convert to NumPy array
img_array = np.array(img)

# Display the image
img.show()

Filename: OIP.jpeg
Format: JPEG
Mode: RGB
Size (width, height): (384, 234)


In [99]:
# Define the new size as a tuple (width, height)
new_size = (200, 150)

# Resize the image
resized_img = img.resize(new_size)

# Save the resized image
resized_img.save('resized_image.jpg')

In [100]:
img_array

array([[[ 57,  43,  56],
        [ 56,  42,  55],
        [ 57,  43,  56],
        ...,
        [ 64,  61,  72],
        [ 64,  62,  73],
        [ 65,  63,  74]],

       [[ 57,  43,  56],
        [ 56,  42,  55],
        [ 57,  43,  56],
        ...,
        [ 63,  61,  72],
        [ 64,  62,  73],
        [ 65,  63,  74]],

       [[ 57,  44,  54],
        [ 57,  44,  54],
        [ 57,  44,  54],
        ...,
        [ 63,  62,  70],
        [ 64,  63,  71],
        [ 64,  64,  72]],

       ...,

       [[ 18,  20,  32],
        [ 21,  24,  33],
        [ 24,  26,  38],
        ...,
        [ 12,  32,  82],
        [ 14,  30,  79],
        [ 13,  30,  76]],

       [[ 18,  21,  30],
        [ 20,  23,  30],
        [ 23,  26,  35],
        ...,
        [ 11,  31,  82],
        [  6,  22,  71],
        [ 45,  62, 108]],

       [[ 18,  21,  28],
        [ 20,  23,  30],
        [ 23,  26,  33],
        ...,
        [ 11,  31,  82],
        [  6,  22,  71],
        [ 45,  62, 108]]

In [101]:
img_array.shape

(234, 384, 3)

In [102]:
img_array.ndim

3