## NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3,4,5])
print(a1)
a1.ndim


# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1,2,3,4],[4,5,6,7]])
print(a2)
a2.ndim

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a3)
a3.ndim

[1 2 3 4 5]
[[1 2 3 4]
 [4 5 6 7]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


3

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
print(a1.shape)
print(a1.ndim)
print(a1.dtype)
print(a1.size)
print(type(a1))

(5,)
1
int64
5
<class 'numpy.ndarray'>


In [4]:
# Attributes of 2-dimensional array
print(a2.shape)
print(a2.ndim)
print(a2.dtype)
print(a2.size)
print(type(a2))

(2, 4)
2
int64
8
<class 'numpy.ndarray'>


In [5]:
# Attributes of 3-dimensional array
print(a3.shape)
print(a3.ndim)
print(a3.dtype)
print(a3.size)
print(type(a3))

(2, 2, 3)
3
int64
12
<class 'numpy.ndarray'>


In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(a2)
df

,0,1,2,3
0,1,2,3,4
1,4,5,6,7


In [7]:
# Create an array of shape (10, 2) with only ones
arr_ones = np.ones((10,2))
arr_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
# Create an array of shape (7, 2, 3) of only zeros
arr_zeros = np.zeros((7,2,3))
arr_zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
# Create an array within a range of 0 and 100 with step 3
arr_range = np.arange(0,101,3)
arr_range

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [10]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.seed(7) #---->> using seed 7 , everytime we run this always get same random number
arr_random = np.random.randint(0,11,(7,2))
arr_random

array([[ 4,  9],
       [ 6,  3],
       [ 3,  7],
       [ 7,  9],
       [ 7,  8],
       [ 9, 10],
       [10,  8]], dtype=int32)

In [11]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
arr_random_float = np.random.rand(3,5)
print(arr_random_float)
print(arr_random_float.dtype)

[[0.4998825  0.67923    0.80373904 0.38094113 0.06593635]
 [0.2881456  0.90959353 0.21338535 0.45212396 0.93120602]
 [0.02489923 0.60054892 0.9501295  0.23030288 0.54848992]]
float64


In [12]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
arr_rand = np.random.randint(0,11,(4,6))
arr_rand

array([[ 6,  3, 10,  7,  4,  6],
       [ 9,  2,  6, 10, 10,  7],
       [ 4,  3,  7,  7,  2,  5],
       [ 4,  1,  7,  5,  1,  4]], dtype=int32)

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [13]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
var = np.random.randint(1,11,(3,7))


# Find the unique numbers in the array you just created
unique_number = np.unique(var)
print(var)
print("unique number in the array : ")
print(unique_number)

[[ 1 10  6  9  1 10  3]
 [ 7  4  9  3  5  3  7]
 [ 5  9  7  2  4  9  2]]
unique number in the array : 
[ 1  2  3  4  5  6  7  9 10]


In [14]:
# Find the 0'th index of the latest array you created
var[0]

array([ 1, 10,  6,  9,  1, 10,  3], dtype=int32)

In [15]:
# Get the first 2 rows of latest array you created
var[:2]

array([[ 1, 10,  6,  9,  1, 10,  3],
       [ 7,  4,  9,  3,  5,  3,  7]], dtype=int32)

In [16]:
# Get the first 2 values of the first 2 rows of the latest array
var[:2,:2]

array([[ 1, 10],
       [ 7,  4]], dtype=int32)

In [17]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array = np.random.randint(0,11,(3,5))
ones_array = np.ones((3,5))
print(random_array)
print(ones_array)

[[9 8 9 4 1]
 [3 6 7 2 0]
 [3 1 7 3 1]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [18]:
# Add the two arrays together
added_array = random_array+ones_array
added_array

array([[10.,  9., 10.,  5.,  2.],
       [ 4.,  7.,  8.,  3.,  1.],
       [ 4.,  2.,  8.,  4.,  2.]])

In [19]:
# Create another array of ones of shape (5, 3)
arr_ones_another = np.ones((5,3))
arr_ones_another

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
# Try add the array of ones and the other most recent array together
added_array2 = added_array.reshape(5,3)+arr_ones_another
added_array2

array([[11., 10., 11.],
       [ 6.,  3.,  5.],
       [ 8.,  9.,  4.],
       [ 2.,  5.,  3.],
       [ 9.,  5.,  3.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?
ans: i have reshaped the array added_array from (3,5) to (5,3) to add as they have to be of same shape

In [21]:
# Create another array of ones of shape (3, 5)
arr_ones3 = np.ones((3,5))
arr_ones3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
# Subtract the new array of ones from the other most recent array
sub_array = added_array2.reshape(3,5) - arr_ones3
sub_array

array([[10.,  9., 10.,  5.,  2.],
       [ 4.,  7.,  8.,  3.,  1.],
       [ 4.,  2.,  8.,  4.,  2.]])

In [23]:
# Multiply the ones array with the latest array
mul_array = arr_ones3 * sub_array
mul_array

array([[10.,  9., 10.,  5.,  2.],
       [ 4.,  7.,  8.,  3.,  1.],
       [ 4.,  2.,  8.,  4.,  2.]])

In [24]:
# Take the latest array to the power of 2 using '**'
power_arr = mul_array ** 2
power_arr

array([[100.,  81., 100.,  25.,   4.],
       [ 16.,  49.,  64.,   9.,   1.],
       [ 16.,   4.,  64.,  16.,   4.]])

In [25]:
# Do the same thing with np.square()
square_arr = np.square(mul_array)
square_arr

array([[100.,  81., 100.,  25.,   4.],
       [ 16.,  49.,  64.,   9.,   1.],
       [ 16.,   4.,  64.,  16.,   4.]])

In [26]:
# Find the mean of the latest array using np.mean()
mean = np.mean(square_arr)
mean

np.float64(36.86666666666667)

In [27]:
# Find the maximum of the latest array using np.max()
max = np.max(square_arr)
max

np.float64(100.0)

In [28]:
# Find the minimum of the latest array using np.min()
min = np.min(square_arr)
min

np.float64(1.0)

In [29]:
# Find the standard deviation of the latest array
sd = np.std(square_arr)
sd

np.float64(34.91869922485022)

In [30]:
# Find the variance of the latest array
variance = np.var(square_arr)
variance

np.float64(1219.3155555555554)

In [31]:
# Reshape the latest array to (3, 5, 1)
reshaped_array = square_arr.reshape(3,5,1)
reshaped_array

array([[[100.],
        [ 81.],
        [100.],
        [ 25.],
        [  4.]],

       [[ 16.],
        [ 49.],
        [ 64.],
        [  9.],
        [  1.]],

       [[ 16.],
        [  4.],
        [ 64.],
        [ 16.],
        [  4.]]])

In [32]:
# Transpose the latest array
transposed_array = np.transpose(reshaped_array)
transposed_array

array([[[100.,  16.,  16.],
        [ 81.,  49.,   4.],
        [100.,  64.,  64.],
        [ 25.,   9.,  16.],
        [  4.,   1.,   4.]]])

What does the transpose do?

In [33]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
first_array = np.random.randint(0,11,(3,3))
second_array = np.random.randint(0,11,(3,2))
print(first_array)
print(second_array)

[[5 5 9]
 [3 5 1]
 [9 1 9]]
[[3 7]
 [6 8]
 [7 4]]


In [34]:
# Perform a dot product on the two newest arrays you created
dot = np.dot(first_array,second_array)
dot

array([[108, 111],
       [ 46,  65],
       [ 96, 107]], dtype=int32)

In [35]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
rand_arr4 = np.random.randint(0,11,(4,3))
rand_arr5 = np.random.randint(0,11,(4,3))
print(rand_arr4)
print(rand_arr5)

[[1 4 7]
 [9 8 8]
 [0 8 6]
 [8 7 0]]
[[ 7  7 10]
 [ 2  0  7]
 [ 2  2  0]
 [10  4  9]]


In [36]:
# Perform a dot product on the two newest arrays you created
dot2 = np.dot(rand_arr4,rand_arr5)
dot2

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [ ]:
#first we have to reshape one of the array
dot2 = np.dot(rand_arr4.reshape(3,4),rand_arr5)
dot2

array([[119,  57, 119],
       [152,  88, 208],
       [ 72,  56, 116]], dtype=int32)

It doesn't work. How would you fix it?

In [ ]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
dot3 = np.dot(np.transpose(rand_arr4),rand_arr5)
dot3

array([[105,  39, 145],
       [130,  72, 159],
       [ 77,  61, 126]], dtype=int32)

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [ ]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
rand_arr6 = np.random.randint(0,11,(3,3))
rand_arr7 = np.random.randint(0,11,(3,3))
print(rand_arr6)
print(rand_arr7)

[[6 9 8]
 [6 8 7]
 [1 0 6]]
[[ 6  7  4]
 [ 2  7  5]
 [10  2  0]]


In [ ]:
# Compare the two arrays with '>'
rand_arr6>rand_arr7

array([[False,  True,  True],
       [ True,  True,  True],
       [False, False,  True]])

What happens when you compare the arrays with `>`?
it compares the individual element in the array and returns boolean

In [ ]:
# Compare the two arrays with '>='
rand_arr6>=rand_arr7

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False,  True]])

In [ ]:
# Find which elements of the first array are greater than 7
rand_arr6>7

array([[False,  True,  True],
       [False,  True, False],
       [False, False, False]])

In [ ]:
# Which parts of each array are equal? (try using '==')
rand_arr6 == rand_arr7

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

In [ ]:
# Sort one of the arrays you just created in ascending order
np.sort(rand_arr6)

array([[6, 8, 9],
       [6, 7, 8],
       [0, 1, 6]], dtype=int32)

In [ ]:
# Sort the indexes of one of the arrays you just created
np.argsort(rand_arr6)


array([[0, 2, 1],
       [0, 2, 1],
       [1, 0, 2]])

In [ ]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(rand_arr6)

np.int64(1)

In [ ]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(rand_arr6)

np.int64(7)

In [ ]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(rand_arr6,axis=1)

array([1, 1, 2])

In [ ]:
# Find the indexes with the minimum values across the 0thFind the index with the maximum value in one of the arrays you've created axis (axis=0)
# of one of the arrays you created
np.argmin(rand_arr6,axis=0)
np.argmax(rand_arr6,axis=0)

array([0, 0, 0])

In [ ]:
# Create an array of normally distributed random numbers

# 10 random numbers from a normal distribution (mean=0, std=1)
arr = np.random.normal(0, 1, 10)
print(arr)

[ 0.32684522 -0.08111895  0.46779475  0.73612235 -0.77970188 -0.84389636
 -0.15053386 -0.96555767  0.15048908 -0.11342125]


In [ ]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,num=10)


array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Create a 2D array

In [ ]:
# 3x4 array of normally distributed numbers
arr = np.random.normal(loc=0, scale=1, size=(3, 4))
print(arr)

[[ 2.63352822 -1.02509089 -0.78204783  0.42394307]
 [ 0.8727051   2.28722598  1.6229205   0.82373308]
 [ 0.29305925  0.89663038 -0.61032202 -0.3161659 ]]


## Parameters

loc → mean (μ)

scale → standard deviation (σ)

size → shape of array

## Example with custom mean and std

In [ ]:
# mean = 50, std = 5, 2 rows × 3 columns
arr = np.random.normal(50, 5, (2, 3))
print(arr)


[[42.58787877 48.85576242 54.81320645]
 [48.95153782 46.12978535 48.20110927]]


## Alternative (recommended modern NumPy)

In [ ]:
rng = np.random.default_rng()
arr = rng.normal(0, 1, (3, 4))
print(arr)


[[-1.13284177 -1.17027535 -1.52899433  0.14243172]
 [ 0.22678314 -0.83631116  0.00638601  1.95641433]
 [-0.24949038 -1.05656209  0.25323807 -2.43652561]]


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.