### Creating Numpy Arrays

In [99]:
# Create a One-dimensional Array
# Importing NumPy Array np.array
import numpy as np

a = np.array([1,2,3])
print(a)
# this is a one dimenisonal array

[1 2 3]


In [100]:
# the dimensions of the array.
a.shape

(3,)

In [101]:
# the number of axes (dimensions) of the array.
a.ndim

1

In [102]:
# the total number of elements of the array. 
a.size

3

In [103]:
# an object describing the type of the elements in the array. 
a.dtype

dtype('int64')

In [104]:
# the size in bytes of each element of the array. 
a.itemsize

8

In [105]:
# the buffer containing the actual elements of the array. Normally, we won’t need to use 
a.data

In [106]:
# Creating an array using np.array() method
arr = np.array([10, 20, 30, 40, 50])
print(arr)

# create a another One-dimensional Array with 10 elements
b=np.array([1,2,3,4,5,6,7,8,9])
print(b)

[10 20 30 40 50]
[1 2 3 4 5 6 7 8 9]


# Creating an array using Multi-dimensional 2D and 3D array method

In [107]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [108]:
b.shape

(2, 3)

In [109]:
# create a 2d array with shape 3*3
np.array([[1,2,3],[1,2,3],[1,2,3]]).ndim

2

In [110]:
# create a another 2d array of shape 4*4
np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]])

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [111]:
# create a another 2d array of 2*3
np.array([[1,2,3],[1,2,3]]).ndim

2

In [112]:
#create a 3d array with shape 2*2*2
np.array([[[1,2],[1,2]],[[1,2],[1,2]]]).ndim

3

In [113]:
# create a 3d array with 3*3*3 shape
np.array([[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]]]).ndim

3

# Note 
2 means 1d 

2*2 means 2d

2*2*2 means 3d

2*2*2*2 means 4d array

In [114]:
# create a array with a shape 3*3*3
np.array([[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]]]).shape

(3, 3, 3)

In [115]:
# create a array with a shape 2*1*2
np.array([[[1,2]],[[1,2]]]).shape

(2, 1, 2)

In [116]:
# dtype
np.array([1,2,3], dtype=float)

array([1., 2., 3.])

In [117]:
# create with a dtype a int
# dtype
np.array([1,2,3], dtype=int)

array([1, 2, 3])

### Initialize a Python NumPy Array Using Special Functions
NumPy provides several built-in functions to generate arrays with specific properties.

- np.zeros(): Creates an array filled with zeros.
- np.ones(): Creates an array filled with ones.
- np.full(): Creates an array filled with a specified value.
- np.arange(): Creates an array with values that are evenly spaced within a given range.
- np.linspace(): Creates an array with values that are evenly spaced over a specified interval.

In [118]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [119]:
# create a array using a arrange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [120]:
x = 5          # integer scalar
y = 3.14       # float scalar
z = True       # boolean scalar

In [121]:
# with reshape
np.arange(16).ndim

1

In [122]:
# with reshape
np.arange(16).reshape(2,2,2,2).ndim

4

In [123]:
# your task create a 45 elements array and then reshape it 
# with reshape
np.arange(45).reshape(3,3,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]]])

In [124]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [125]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [126]:
# np.random
np.random.random((3,4))

array([[0.70627944, 0.87020199, 0.25436332, 0.33284876],
       [0.24309596, 0.80836264, 0.60606995, 0.74837995],
       [0.47875959, 0.37509426, 0.81936267, 0.67606174]])

In [127]:
# Creates an array with values that are evenly spaced over a specified interval.
# np.linspace(0, 1, 5)  # start, stop, num
# np.linspace 
np.linspace(-10, 10, dtype=int)

array([-10, -10, -10,  -9,  -9,  -8,  -8,  -8,  -7,  -7,  -6,  -6,  -6,
        -5,  -5,  -4,  -4,  -4,  -3,  -3,  -2,  -2,  -2,  -1,  -1,   0,
         0,   1,   1,   1,   2,   2,   3,   3,   3,   4,   4,   5,   5,
         5,   6,   6,   7,   7,   7,   8,   8,   9,   9,  10])

In [128]:
# np.linspace
np.linspace(-5,5,10,dtype=int)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  5])

In [129]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [130]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [131]:
# ndim
a3.ndim

3

In [132]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [133]:
# size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [134]:
# itemsize
a3.itemsize

8

In [135]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


### Changing Datatype

In [136]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [137]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [138]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [139]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [140]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [141]:
# vector operations
# arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

### Array Functions

In [142]:
a1 = np.random.random((3,3))
a1

array([[0.40938666, 0.92095624, 0.98505448],
       [0.48543546, 0.8019481 , 0.1132336 ],
       [0.05662121, 0.52405599, 0.4304703 ]])

In [143]:
a1 = np.round(a1*100)
a1

array([[41., 92., 99.],
       [49., 80., 11.],
       [ 6., 52., 43.]])

In [144]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.prod(a1,axis=0)

array([ 12054., 382720.,  46827.])

In [145]:
np.max(a1)

np.float64(99.0)

In [146]:
np.min(a2)

np.int64(12)

In [147]:
# mean/median/std/var
np.var(a1)

np.float64(955.3580246913581)

In [148]:
# trigonomoetric functions
np.sin(a1)

array([[-0.15862267, -0.77946607, -0.99920683],
       [-0.95375265, -0.99388865, -0.99999021],
       [-0.2794155 ,  0.98662759, -0.83177474]])

In [149]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [150]:
# log and exponents
np.exp(a1)

array([[6.39843494e+17, 9.01762841e+39, 9.88903032e+42],
       [1.90734657e+21, 5.54062238e+34, 5.98741417e+04],
       [4.03428793e+02, 3.83100800e+22, 4.72783947e+18]])

### np.ceil() → Ceiling

Definition: Rounds each number UP to the nearest integer.

Always goes toward +∞, no matter what.

In [151]:
import numpy as np

arr = np.array([1.2, 2.7, -1.5, -2.3])
arr

array([ 1.2,  2.7, -1.5, -2.3])

In [152]:
np.ceil(arr)

array([ 2.,  3., -1., -2.])

### np.floor() → Floor

Definition: Rounds each number DOWN to the nearest integer.

Always goes toward -∞.

In [153]:
np.floor(arr)

array([ 1.,  2., -2., -3.])

### np.round() → Round (to nearest)

Definition: Rounds each number to the nearest integer.

If decimal = 0.5 → rounds to nearest even integer (NumPy behavior).

In [154]:
np.round(arr)

array([ 1.,  3., -2., -2.])

### Indexing and Slicing

In [155]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [156]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [157]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [158]:
a2[1,0]

np.int64(4)

In [159]:
a2[1,2]

np.int64(6)

In [160]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [161]:
a3[1,0,1]

np.int64(5)

In [162]:
a3[0,1,0]

np.int64(2)

In [163]:
### find the elements 7
a3[1,1,1]

np.int64(7)

In [164]:
# find elements 3
a3[0,0,1]

np.int64(1)

In [165]:
# whats the output
a3[1,1,0]

np.int64(6)

In [166]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [167]:
a1[2:5:2]

array([2, 4])

In [168]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [169]:
a2[0:2,1:2]

array([[1],
       [5]])

In [170]:
# find the elements 9 and like aobove
a2[2,1:3]

array([ 9, 10])

In [171]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [172]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [173]:
a2[:,2:3]

array([[ 2],
       [ 6],
       [10]])

In [174]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [175]:
### now make a question and solve it 
# find the elements 14 and 17
a2[1,2:4]

array([6, 7])

In [176]:
a2[1,::3]

array([4, 7])

In [177]:
a2[0,:]

array([0, 1, 2, 3])

In [178]:
a2[:,2]

array([ 2,  6, 10])

In [179]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [180]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [181]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [182]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [183]:
a3[0,1,:]

array([3, 4, 5])

### Iterating

In [184]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [185]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [186]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [187]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [188]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [189]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [190]:
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [191]:
# ravel
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [192]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [193]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [194]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [195]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [196]:
from PIL import Image
import numpy as np

# Open an image file (use a relative or absolute path)
# Load image
img = Image.open("OIP.jpeg")  # your image file

print(f"Filename: {img.filename}")
print(f"Format: {img.format}")
print(f"Mode: {img.mode}")
print(f"Size (width, height): {img.size}")

# Convert to NumPy array
img_array = np.array(img)

# Display the image
img.show()

Filename: OIP.jpeg
Format: JPEG
Mode: RGB
Size (width, height): (384, 234)


In [197]:
# Define the new size as a tuple (width, height)
new_size = (200, 150)

# Resize the image
resized_img = img.resize(new_size)

# Save the resized image
resized_img.save('resized_image.jpg')

In [198]:
img_array

array([[[ 57,  43,  56],
        [ 56,  42,  55],
        [ 57,  43,  56],
        ...,
        [ 64,  61,  72],
        [ 64,  62,  73],
        [ 65,  63,  74]],

       [[ 57,  43,  56],
        [ 56,  42,  55],
        [ 57,  43,  56],
        ...,
        [ 63,  61,  72],
        [ 64,  62,  73],
        [ 65,  63,  74]],

       [[ 57,  44,  54],
        [ 57,  44,  54],
        [ 57,  44,  54],
        ...,
        [ 63,  62,  70],
        [ 64,  63,  71],
        [ 64,  64,  72]],

       ...,

       [[ 18,  20,  32],
        [ 21,  24,  33],
        [ 24,  26,  38],
        ...,
        [ 12,  32,  82],
        [ 14,  30,  79],
        [ 13,  30,  76]],

       [[ 18,  21,  30],
        [ 20,  23,  30],
        [ 23,  26,  35],
        ...,
        [ 11,  31,  82],
        [  6,  22,  71],
        [ 45,  62, 108]],

       [[ 18,  21,  28],
        [ 20,  23,  30],
        [ 23,  26,  33],
        ...,
        [ 11,  31,  82],
        [  6,  22,  71],
        [ 45,  62, 108]]

In [199]:
img_array.shape

(234, 384, 3)

In [200]:
img_array.ndim

3