array[start:stop:step]

arr[start:end], start to end - 1

negative step, -1 reverse
"""

In [1]:
import numpy as np

arr =np.array([1, 2, 3, 4, 5])
print(arr[1:5]) #index from 1 to 4
print(arr[0:4]) #index from 0 to 3
print(arr[2:]) #index from 2 to end
print(arr[:3]) #index from start to 2
print(arr[:]) #index from start to end
print(arr[::2]) #index from start to end with step 2 every other element
print(arr[1::2]) #index from 1 to end with step 2
print(arr[::-1]) #index from end to start with step -1

[2 3 4 5]
[1 2 3 4]
[3 4 5]
[1 2 3]
[1 2 3 4 5]
[1 3 5]
[2 4]
[5 4 3 2 1]
